language: android
dist: trusty
jdk: oraclejdk8


android:
  components:
    - build-tools-26.0.2
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1

# Setup environment
before_install:
  - chmod +x gradlew

before_deploy:
  # Generate a packaged jar for the desktop-project and rename it to include the tag
  - ./gradlew desktop:dist
  - mv desktop/build/libs/desktop-1.0.jar desktop/build/libs/{PROJECT_NAME}-$TRAVIS_TAG.jar
  # Generate a packaged apk for the android-project and rename it (this apk is unsigned/unaligned)
  - ./gradlew android:assembleRelease
  - mv android/build/outputs/apk/android-release-unsigned.apk android/build/outputs/apk/{PROJECT_NAME}-$TRAVIS_TAG-unaligned.apk
  # Generate and zip deployment files for the HTML project
  - ./gradlew html:dist
  - zip -r {PROJECT_NAME}-$TRAVIS_TAG.zip ./html/build/dist/
deploy:
  provider: releases
  api_key:
    secure: {DEPLOYMENT_KEY}
  file:
    # Define which files should be deployed to GitHub
    - desktop/build/libs/{PROJECT_NAME}-$TRAVIS_TAG.jar
    - android/build/outputs/apk/{PROJECT_NAME}-$TRAVIS_TAG-unaligned.apk
    - {PROJECT_NAME}-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: {GITHUB_USER}/{PROJECT_NAME}
    branches: master